### ISSUE TITLE
Image Occlusion Enhanced Runtime Error Anki 2.1.56

### ISSUE THREAD

**Issue by bigmoney456** [glutanimate/image-occlusion-enhanced#279] opened 2023-02-21 03:55 UTC
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [**x**] I've restarted Anki to see if it helps
 - [**x** ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [**x** ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ **x**] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-12.6.3-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-19 21:45:01
Add-ons possibly involved: ⁨Image Occlusion Enhanced⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.theme", line 217, in apply_style_if_system_style_changed
  File "aqt.theme", line 228, in apply_style
  File "_aqt.hooks", line 4678, in __call__
  File "aqt.webview", line 717, in on_theme_did_change
  File "aqt.webview", line 550, in eval
  File "aqt.webview", line 553, in evalWithCallback
  File "aqt.webview", line 570, in _queueAction
  File "/Users/tnadir1/Library/Application Support/Anki2/addons21/1374772155/editor.py", line 107, in _maybeRunActions
    self._evalWithCallback(*args)
  File "aqt.webview", line 566, in _evalWithCallback
RuntimeError: wrapped C/C++ object of type ImgOccWebView has been deleted

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment] 2023-02-23 12:37
Hi there, thanks for the report! A fix for this is already merged into the main branch and will land in the next major update of the add-on. While that is still in the works, I've uploaded an older development build [here](https://github.com/glutanimate/temp-workspace/releases/download/0.0.1/image-occlusion-enhanced-v1.4.0-32-g4e26bd2-qt5+qt6.ankiaddon) that you can install to fix the runtime error.

Closing as duplicate of #251

**Closed as completed by glutanimate** 2023-02-23 12:37 UTC
Labels: duplicate
