### ISSUE TITLE
When studying all the notes behave as separate.

### ISSUE THREAD

**Issue by gunnarmaluf** [glutanimate/image-occlusion-enhanced#31] opened 2017-04-20 18:15 UTC
Hi!

If I create 5 notes they are created as new. 

When I start to review/learn them I review the first one, but all the others
keep showing up. They should be suspended until the next day.

This would help a lot to spread out the knowledge being learnt.

**Comment by glutanimate** [comment] 2017-04-20 20:44
Hey Gunnar,

thanks for the suggestion. I agree that this option would be useful in some instances, but I'm afraid there's no feasible way to implement it at this point. Please see here for more information: https://anki.tenderapp.com/discussions/add-ons/10048-is-there-a-way-to-combine-multiple-cards-into-one-note#comment_42369902

**Comment by glutanimate** [comment] 2017-05-11 13:07
Closing this as a duplicate of #2

**Closed by glutanimate** 2017-05-11 13:07 UTC
