### ISSUE TITLE
image occlusion problem error

### ISSUE THREAD

**Issue by Rayyanto** [glutanimate/image-occlusion-enhanced#278] opened 2023-02-20 19:46 UTC
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

it gives me an error message when I try to add the cards, I believe it is happening after I use the pencil tool on the image as every time I don't use it it works
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 -  [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.58 (ab8b1465) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.2.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-20 18:50:30
Add-ons possibly involved: ⁨Image Occlusion Enhanced⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 604, in handler
  File "/Users/rayyan/Library/Application Support/Anki2/addons21/1374772155/add.py", line 324, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(
  File "/Users/rayyan/Library/Application Support/Anki2/addons21/1374772155/add.py", line 343, in _onAddNotesButton
    r = gen.generateNotes()
  File "/Users/rayyan/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 99, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "/Users/rayyan/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 226, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Comment by glutanimate** [comment] 2023-02-23 12:46
Hi there, thanks for the report. This looks like a duplicate of #220. Unfortunately the pencil tool is somewhat broken at the moment and fixing it would require some fairly major under-the-hood changes to the add-on which right now aren't feasible. So my recommendation for now would be to avoid using it (the next IO update will also contain a help message explaining this instead of showing this error).

**Closed as completed by glutanimate** 2023-02-23 12:46 UTC
Labels: duplicate
