### ISSUE TITLE
Microsoft Visual C++ Runtime Error when starting Anki

### ISSUE THREAD

**Issue by Uitalo** [Glutanimate/image-occlusion-enhanced#22] opened 2016-11-12 20:24 UTC
I received this message after install Imagem occlusion:
![image](https://cloud.githubusercontent.com/assets/13296083/20240650/d335814e-a904-11e6-89db-f5e4a8e8c17a.png)

**Comment by Glutanimate** [comment] 2016-11-12 21:24
Mmh, that's a strange error message. First time I'm seeing something like that.

Ok, let's first confirm that this actually because of the add-on:

1. Go to C:\Users\<username>\Documents\Anki\addons
2. Remove the `image_occlusion_enhanced folder` and `Image Occlusion Enanced.py`
3. (Re)start Anki

If the error message still appears it's likely an error with Anki rather than the add-on. If it's gone it might have actually been an issue with Image Occlusion.

**Comment by uitalo** [comment] 2016-11-13 02:26
Yes, this message disappear after uninstall your add-on. I tried start Anki in an other local, where not there others add-ons, then it worked. So probably there are an conflict with other add-on.

Sorry, but my english not is very good. :(

**Comment by Glutanimate** [comment] 2016-11-13 11:55
Your English is fine, don't worry!

Do you know which other add-ons you had installed? For instance, was this the first time you installed Image Occlusion or did you possibly have an earlier version installed?

**Comment by Uitalo** [comment] 2016-11-13 16:31
I have the old version "image_occlusion_2", but I removed before I install the atual version. The old version is working without conflict. 

My add-ons: 
![image](https://cloud.githubusercontent.com/assets/13296083/20247221/c3e7c3ba-a9ad-11e6-8fbd-237693e21554.png)

**Comment by Glutanimate** [comment] 2016-11-13 19:08
Ok, thanks for the screenshot. I can't really see anything that could cause this.

Sorry, I would like to help you with this, but I have no clue what's wrong. The only thing I can suggest would be to start from a clean slate, without any add-ons installed, then install IO and add each other add-on one by one while restarting Anki again and again. At some point the error should reappear and that should tell you where the conflict lies. This a very tedious process, but it's the only way I can think of to troubleshoot this because the error message is way too general to identify the cause.

**Comment by Uitalo** [comment] 2016-11-13 21:01
" When you say you've managed to install it successfully in another "local", do you mean another Windows user account or another PC?"
In same windows user account, but in other folder. 

I'll try your suggestion.
Thank you.

**Comment by Glutanimate** [comment] 2016-12-01 16:33
Hey @Uitalo,

I think I've identified the issue and found a possible workaround (apparently this is a [longstanding bug](https://bugs.python.org/issue17213) with some Python distributions on Windows).

Could you do me a favor and give [this release](https://github.com/Glutanimate/image-occlusion-enhanced/releases/tag/v1.0.3-beta) a try? You will have to [install it manually](https://github.com/Glutanimate/image-occlusion-enhanced/wiki/Installation#manual-installation), but it should hopefully fix the bug permanently.

**Comment by Glutanimate** [comment] 2016-12-04 22:31
This seems to be fixed with the latest stable release, so I'll mark this as solved. However, please feel free to comment here if you ever run into this issue again.

**Closed by Glutanimate** 2016-12-04 22:31 UTC
Labels: bug
