### ISSUE TITLE
SVG-Edit doesn't load properly when Anki path contains special characters

### ISSUE THREAD

**Issue by TTPorter** [glutanimate/image-occlusion-enhanced#13] opened 2016-06-10 09:51 UTC
This add on is a great development, it is quite efficient, and it is exactly what I am looking for.
Unfortunately, it seems not working well on my laptop, and I can't figure out why.
After I pressed the button "Image Occlusion" or "Alt+o" to start it and chose the image to be editted, the window "Image Occlusion 2.0 Enhanced Editor" showed up. But within this window, there were no toolbar or buttons for image editting, and the image just doesn't load. Just as the attached file shows.
Can someone help with Image Occlusion problem please?
http://7xrn7f.com1.z0.glb.clouddn.com/16-6-10/52606921.jpg

**Comment by Glutanimate** [comment] 2016-06-10 10:39
Hi,

that seems strange, indeed.

Please try the following steps if you haven't done so already:

- restart Anki
- restart your PC
- as a last resort: remove and reinstall the add-on

These sound trivial, I know, but they're the best way to figure out where the actual issue lies.

If none of these work I'll need some more information to debug this:

- What version of Anki are you using?
- Do you have the latest version of Image Occlusion 2.0 Enhanced installed?
- Which operating system are you on? (Windows 7/Vista/etc.?)

**Comment by TTPorter** [comment] 2016-06-10 10:56
Thank you very very much for your rapid reply!
I have tried the those steps twice,  and the issue remains.
My Anki version is 2.0 2.0.36, and I have installed Image Occlusion  2.0 Enhanced with 1111933094.
I also have tried the earlier version of Image Occlusion 2.0 (2006541756).
I have try it on windows xp and windows 7, and sadly to find it doesn't  work neither.

It seems that the svg editor just doesn't start for some reasons.

**Comment by Glutanimate** [comment] 2016-06-10 11:08
Ok, thanks for giving these a try. The bad news is that I can't reproduce the issue on my own Windows machine (Win7 + Anki 2.0.36). Can't think of anything else for you to try right now. However, it might be worth a shot opening a new thread on [Anki's add-on support forums](https://anki.tenderapp.com/discussions/add-ons). Maybe you'll find someone who's run into the same issue in the past and might be able to help you (especially given that you're also experiencing the issue when using the original version of Image Occlusion).

**Comment by Glutanimate** [comment] 2016-06-10 11:10
Maybe one last suggestion: Have you tried creating a new Anki profile and seeing if IO works there? (You can do this by going to File → Switch profile).

**Comment by TTPorter** [comment] 2016-06-10 11:33
Thank you very much for your help!
I'll keep on finding the solution.

**Comment by TTPorter** [comment] 2016-06-13 00:14
Problem solved!
https://anki.tenderapp.com/discussions/add-ons/7636-image-occlusion
As ruz advised, I‘ve changed my profile folder into a shorter path which contains only Latin characters. And finally the add-on starts working perfectly! 
I love this development!

**Comment by Glutanimate** [comment] 2016-06-13 07:46
That's great to hear! Thanks for telling me. I'll add a warning on this to the add-on description when I have some more time on my hands.

**Comment by Glutanimate** [comment] 2017-03-05 17:29
Hi @TTPorter,
seeing how it has been a while since the last reports about this issue, I was wondering if you still have to use the profile workaround for the add-on to work? The add-on has undergone quite a few changes over the past few months, so I thought it would be a good idea to check if these issues are actually still present.

**Comment by Glutanimate** [comment] 2017-03-31 18:47
Closing this for now as it looks like it is no longer an issue.

**Comment by kimdohun1205** [comment] 2018-03-20 19:41
I can upload images to a regular note card .but after click image icon and choose image,Image file does not appear on occlusion enhanced editor.

The content of this eagle is the same as my current situation.

https://anki.tenderapp.com/discussions/add-ons/7636-image-occlusion

I've already tried deleting or rebooting

It is possible, that path to the profile contain non-Latin characters. If so, try to change path to the profile in the settings. A shorter path, like c:\ankidata could make add-on work.

I do not understand it as a Google translator. Could you tell me how to change the path to a picture or video?  my mail is rlatjdqo1205@naver.com or kimdohun1205@gmail.com
Please help me﻿

**Comment by glutanimate** [comment] 2018-03-21 13:36
@kimdohun1205 Thanks. I will try looking into this soon.

**Comment by kimdohun1205** [comment] 2018-03-22 11:33
Sorry, I checked yesterday, but I got the account name in English in
Windows 7.
I logged off and tried to use korean as an English account but it was only
an English account.
In Windows 10, even if you have an account name in English, @ is in your
email account.

2018-03-21 22:36 GMT+09:00 Aristotelis <notifications@github.com>:

**Comment by glutanimate** [comment] 2018-06-28 21:21
Hey guys,

I'm happy to say that this issue appears to be fixed on Anki 2.1 (#47)!

If you're interested in helping me test this make sure to stay tuned to this thread: I will be releasing an alpha release of the add-on over the next few days.

**Closed** 2018-06-28 21:22 UTC
Labels: anki2.0, bug, windows

**Comment by SamuelAllain** [comment] 2024-04-29 11:50
Hello ! Thanks @glutanimate for your great add-on !
I still experience the bug with a profile prefixed with a "#" (Anki Version ⁨23.12.1, add-on 1.4.0 - 2022-04-09). I used this "#" to put the profile as the first one in alphabetical order but then it was impossible to edit an Image-Occlusion note. Removing the "#" solved the issue, thanks @TTPorter for the solution !

**Comment by JohnGreat234** [comment] 2025-01-28 16:24
Hi, I have the problem which the editor refuses to appear. I have done everything the wiki article told me to do, but it still does not work. Is there something I can do? I am really desperate to continue studying...
